### ISSUE TITLE
Add AUTH

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-edge#14]
@RaiBnod to decide on this

in the command to start the server please make sure the auth can be disabled

The token works for me the same as FF but its up to @RaiBnod

**Comment by RaiBnod** [comment]
As `auth` needs to be controlled by the developers only:
- we need to remove that from config so users can't edit it and bypass the auth and 
- give developers that `--auth` option from the command line, so developers can add and remove it
