### ISSUE TITLE
add api for getting logs

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-edge#29]
Please note that on our gateway that log storage on disc is disabled, so we would need to stream the logs
Eg stream logs for 30 sec and return the data to the user
https://github.com/NubeIO/lib-journalctl

**Comment by RaiBnod** [comment]
- SEND post with duration=60 and return a UUID (don't wait 60 sec just return UUID)
- Then the user will GET the UUID eg 60 sec later
- After the user GET the data to that UUID then destroy the UUID/DATA
- On restart of edge all existing logs with UUID get deleted from memory
