### ISSUE TITLE
complete backup and restore of /data

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-edge#44]
We need to have a way for the user to back up and restore the whole device

The are 2x use cause

1. user takes a zip backup and 1 year later the device breaks and they want a complete restore of all the device info and uuids
2. user takes a backup of device-a and wants to save it in device-b as they are both the same application, but we need to keep the device info as in its wires-plat info. this will mean that the all the network and device UUIDs will be the same

option 2 is actually the more common use case. its needed a lot to save time for people

**Comment by RaiBnod** [comment]
### Scope of work

- To snapshot the all apps and data

#### Backup

- Copy all `/data` as a `data`
- Copy all `/lib/systemd/system/nubeio-*` as `system`
   - Here is an example: https://github.com/NubeIO/k8s-nubeio-suite-customer/blob/master/templates/rubix/nubeio-rubix-deployment.yaml#L82-L89 (exclude OpenVPN)
- Create a `<client_name>-<site_name>-<device_name>_<ISO timestring>.zip` file (snapshot) with those above two files
- Have an API to do this, which will respond that the `.zip` snapshot
   - It will get called from `rubix-assist` < `rubix-ui`

#### Restore

- Have an API to accept the `.zip` snapshot (add flag `use_old_global_uuid=<bool>`, default is false)
- Restore `data` to `/data`, replace all in case of already file existence
   - If `use_old_global_uuid=false` then, edit `/data/rubix-registry/device_info.json` and make `global_uuid` as empty string `("")`
- Restore `system` files to `/lib/systemd/system/`
- Enable and restart all the apps
   - Here is an example: https://github.com/NubeIO/k8s-nubeio-suite-customer/blob/master/templates/rubix/nubeio-rubix-deployment.yaml#L70-L75
