### ISSUE TITLE
CRON job restarting the apps, services & host

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-edge#67]
It needs to be similar to the rubix-service scheduler to restart the apps and services. But it needs to be CRON job like restarting mechanism, rubix-service couldn't able to schedule the restart like if we want to restart the service every day at 1 AM.

Also, the device restart CRON job is needed.

**Comment by NubeDev** [comment]
i think its better to add these in RA, the idea is to reduce the amout of code in RE
https://github.com/NubeIO/rubix-assist/issues/99

**Comment by RaiBnod** [comment]
But if we do this on RA, and it gets disconnected from the internet it won't get restarted at the correct time.

**Comment by RaiBnod** [comment]
We decided to put this logic here instead of having it in RA.
